---
title: Memoirs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'Votre source de nouvelles par excellence !

'
baseurl: 
url: http://www.lejournallenord.com/
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
